### PR TITLE
implement instance Generic Version

### PR DESCRIPTION
**Pull request by KtorZ**
Hey!

I've added a `Generic Version` instance and some associated tests (using `gShow`).

Let me know what you think about it.

### CODE REVIEW

**Comment by hdgarrood** [comment]
Hi :) Sorry, I don't think this is a good idea. If we were going to give Version a Generic instance, people would expect it to behave like the derived instance. Also, I think code which uses generic instances might start behaving weirdly if we tell it that a Version is just a String (when I'd course that's not true).

**Comment by hdgarrood** [comment]
Hi :) sorry, I don't think I want to merge this. If we were going to give Version a Generic instance, people would expect it to behave like the derived instance. Also, I think code which uses generic instances might start behaving weirdly if we tell it that a Version is just a String (when of course that's not true).

**Comment by KtorZ** [comment]
I would be really interested to know the rational behind your choice (I am trying to get a bit familiar with Generics) :)

How would a Version not be considered as a String ?

**Comment by hdgarrood** [comment]
"asdflasdfj;l" is a String, but clearly it's not a Version. By saying that the signature of Version is SigString, as this instance does, I think it would be reasonable for other code to simply assume that any spine that's just a string will succeed in being converted to a Version, but this isn't the case here.

Please feel free to use a newtype with this instance in your own projects if you want to, but I don't think it's the right choice for this library.

**Pull request closed without merging**
